[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
aes-gcm = "0.10" 
aead = "0.5"
rand = "0.8"
pbkdf2 = "0.10"
hmac = "0.12"
sha2 = "0.10"
thiserror = "1.0" 